spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: currency-exchange
          uri: lb://currency-exchange
          predicates:
            - Path=/currency-exchange/**
        - id: currency-conversion
          uri: lb://currency-conversion
          predicates:
            - Path=/currency-conversion/**
server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

#Zipkin Configuration
management:
  tracing:
    sampling:
      probability: 1
